### PR TITLE
Added support 41 gnome

### LINKED ISSUE #18: Gnome 41 Support
This isn't currently supported on Gnome 41. Any plans to update it?

I've got it running by editing the metadata.json and in sudo mode it successfully detects the status, going light and dark depending on if it's running. The toggles don't work though. It toggles off, doesn't ask for a password, and then toggles back on

nmcli mode doesn't show any toggles at all

Everything else seems fine

### PR DESCRIPTION
**Pull request by Toxblh**
Tested. Works all good.

Close #18

### CODE REVIEW

**Comment by JKomoroski** [comment]
bump :)

**Comment by jibsaram** [comment]
Just wanted to chime in with a confirmation from my end, by manually adding 41 locally, the extension is working just like before. In case it helps, I'm relying on `nmcli`.

**Comment by kinduff** [comment]
bump!

**Review by kinduff — APPROVED** [review]

**Comment by alexanderi96** [comment]
any news?

**Comment by zilexa** [comment]
Is this now merged/added/released?

**Comment by Toxblh** [comment]
@atareao could you merge and release a new version to extensions?

**Comment by SerhiyRomanov** [comment]
@atareao I hope you are doing well. Could you make a release with Gnome 41 support?

**Comment by kinduff** [comment]
Thank you so much @atareao !

**Pull request merged**
