### PR TITLE
Add support for gnome 43

### PR DESCRIPTION
**Pull request by jaras2678**
The tested extension works fine

### CODE REVIEW

**Comment by Zackptg5** [comment]
I'm not sure if this extension is needed anymore in gnome 43. There's a VPN section now in the new quick settings menu that serves the same purpose this extension does

**Comment by fabrixxm** [comment]
@Zackptg5 I'm probably missing something, but my VPN settings in GNOME does not support Wireguard

**Comment by Zackptg5** [comment]
@fabrixxm I had to import them with nmcli in terminal and then they show up in quick network settings menu but I haven't gotten gui in settings to work with it yet either

**Comment by adasauce** [comment]
Ah! I thought the extension had moved somehow. I noticed the new vpn section the other day. It looks like it's not required for me anymore,

Thanks to the dev for developing and maintaining this! It got me by for a while now.

**Pull request merged**
